[NCL-6963] Create sorting component and integrate it
project-ncl/pnc-web-ui-react pull request #101
Opened 2022-09-15 09:40 UTC by patrikk0123

2022-10-11 08:20 UTC, matedo1 requested changes

2022-10-12 09:50 UTC, patrikk0123 commented on src/components/Sorting/Sorting.tsx
> +        const urlSortOrder = currentSortParam.split('=')?.[1];
I decided to create separate validateSortParam function.

2022-10-12 14:13 UTC, matedo1 approved these changes

2022-10-12 14:14 UTC, merged

2022-10-12 14:35 UTC, matedo1 commented
see also related PR https://github.com/project-ncl/pnc-web-ui-react/pull/111