[NCL-6146] Integrate Web UI logging service with Web UI
project-ncl/pnc-web-ui-react pull request #114
Opened 2022-10-20 10:50 UTC by patrikk0123

2022-10-27 12:23 UTC, matedo1 requested changes

2022-10-27 12:23 UTC, matedo1 commented on src/services/userService.ts
> +class UserService {
we should split it into UserService (API communication, just functions, not class) and UserManager (user state management)

2022-10-27 12:23 UTC, matedo1 commented on src/utils/uiLoggerHelper.ts
> +  const uiLogData = createData(message, error, additionalData);
`log()` method can be used here to prevent duplication

2022-10-27 12:23 UTC, matedo1 commented on src/utils/uiLoggerHelper.ts
> +export const uiLogger = { log, error, createData };
`createData` should not be exported

2022-10-27 12:23 UTC, matedo1 commented on src/utils/uiLoggerHelper.ts
> +export interface ExtendedError extends Error {
should not be exported and all conversion should be in this file

2022-10-27 12:23 UTC, matedo1 commented on src/components/ErrorBoundary/ErrorBoundary.tsx
> +    uiLogger.error(undefined, error as ExtendedError);
`errorInfo` should be probably passed as `additionalData` parameter

2022-10-27 12:29 UTC, patrikk0123 commented on src/services/WebConfigService.ts
> +  // url should be contained in web config, but is still missing
done (NCL-7403)

2022-10-31 08:14 UTC, matedo1 requested changes

2022-10-31 08:14 UTC, matedo1 commented on src/services/keycloakService.ts
> +            if (this.isAuthenticated()) {
in this case, it could be enough:

```js
if (this.isAuthenticated()) {
   userManager.fetchUser();
}
resolve('success');
```

2022-10-31 08:14 UTC, matedo1 commented on src/services/userManager.ts
> +  public removeUser() {
I would remove this one, if it's not used or there is no specific already existing use case

2022-11-07 14:45 UTC, jomrazek reviewed
Looks ok to me :+1:

2022-11-08 09:27 UTC, matedo1 commented on src/services/keycloakService.ts
> +            if (this.isAuthenticated()) {
we agreed to keep the original version in the end

2022-11-10 12:43 UTC, matedo1 approved these changes

2022-11-10 12:49 UTC, merged