[NCL-7230] Implement Product Detail page
project-ncl/pnc-web-ui-react pull request #167
Opened 2023-02-28 12:08 UTC by patrikk0123

2023-02-28 15:48 UTC, matedo1 requested changes

2023-02-28 15:48 UTC, matedo1 commented on src/components/ProductDetailPage/ProductDetailPage.tsx
> +    <ServiceContainerLoading {...serviceContainerProduct} title="Project details">
`title="Product details"`

2023-03-03 13:37 UTC, matedo1 commented
Hi guys @patrikk0123 and @DnsZhou , 

`components/ProductDetailPage/ProductDetailPage.tsx` contains bug, would be able to found it? :)

2023-03-06 17:15 UTC, matedo1 requested changes

2023-03-06 17:15 UTC, matedo1 commented on src/services/productsApi.tsx
> +
wrong file name:
1) use singular
2) use `ts` 

so `productApi.ts`

2023-03-07 09:14 UTC, patrikk0123 commented on src/components/ProductDetailPage/ProductDetailPage.tsx
> +    ({ requestConfig } = {}) => serviceContainerProductVersionsRunner({ serviceData: { id: productId }, requestConfig }),
No, it is not, because of typescript error.

2023-03-07 09:48 UTC, matedo1 approved these changes

2023-03-07 09:50 UTC, merged