[NCL-7221] Implement Product List page
project-ncl/pnc-web-ui-react pull request #169
Opened 2023-02-28 13:23 UTC by patrikk0123

2023-02-28 16:21 UTC, matedo1 requested changes

2023-02-28 16:21 UTC, matedo1 commented on src/components/ProductsPage/ProductsPage.tsx
> +    <PageLayout title={PageTitles.products} description={<>This page contains products... TODO</>}>
Description `This page contains list of products like <Label>EAP</Label>, usually product is a deliverable package composed of multiple projects like <Label>JBoss Modules</Label> or <Label>Hibernate<Label>.`

2023-02-28 16:21 UTC, matedo1 commented on src/components/ProductsPage/ProductsPage.tsx
> +    <PageLayout title={PageTitles.products} description={<>This page contains products... TODO</>}>
@jbartece is there anything else you would like to propose for the page description that will be displayed on product list page?

2023-02-28 16:21 UTC, matedo1 commented on src/components/ProductsPage/ProductsPage.tsx
> +      <ContentBox shadow={false} background={false} marginBottom>
Why `ContentBox` is needed?

2023-03-01 16:22 UTC, patrikk0123 commented on src/components/ProductsList/ProductsList.tsx
> +    title: 'Name',
Not for the time being, sorting options structure needs to be changed first. Then title can be removed here and also on **ProjectsList** component.

2023-03-03 13:59 UTC, matedo1 approved these changes

2023-03-07 11:44 UTC, matedo1 approved these changes

2023-03-07 11:45 UTC, merged