[NCL-7224] Implement Milestone Delivered Artifacts page
project-ncl/pnc-web-ui-react pull request #178
Opened 2023-03-14 15:34 UTC by patrikk0123

2023-03-27 02:17 UTC, DnsZhou requested changes
There seems to be a sort error, when sort was triggered, the page returns no data. see screen shots:
![patrikk0123:ncl7224-deliveredArtifactsPage](https://user-images.githubusercontent.com/6870455/227824385-b4c3986e-0426-421d-862b-9fcf7b1928e1.gif)
other than that, the code looks good.
Thanks!

2023-03-27 08:16 UTC, patrikk0123 commented
> There seems to be a sort error, when sort was triggered, the page returns no data.

Thanks for pointing it out, I rebased branch to use new Artifact Table version which does not have Build column, so this should no longer be a problem.

2023-03-27 11:43 UTC, DnsZhou approved these changes

2023-04-04 15:38 UTC, matedo1 commented on src/services/productMilestoneApi.tsx
> + *
Add service data param

2023-04-05 09:23 UTC, merged