NCL-7649 Add SCM extternal link button
project-ncl/pnc-web-ui-react pull request #193
Opened 2023-04-05 03:36 UTC by DnsZhou

Rebased from https://github.com/project-ncl/pnc-web-ui-react/pull/185 due to too many conflicts

2023-04-06 09:46 UTC, patrikk0123 commented on src/components/ScmRepositoryUrl/ScmRepositoryUrl.tsx
> +    : parseExternalScmRepositoryUrl({ url: originalUrl });
What about:

```
interface IScmRepositoryUrlProps {
  scmRepository: SCMRepository;
 variant: 'internal' | 'external';
 isInline?: boolean;
}

export const ScmRepositoryUrl = ({ scmRepository, variant, isInline }: IScmRepositoryUrlProps) => {
    const originalUrl = variant === 'internal'
        ? scmRepository.internalUrl
        : scmRepository.externalUrl
    const parsedUrl = variant === 'internal'
        ? parseInternalScmRepositoryUrl({ url: originalUrl })
        : parseExternalScmRepositoryUrl({ url: originalUrl });
```

2023-04-06 09:46 UTC, patrikk0123 commented on src/utils/utils.ts
> +interface IParsedScmRepositoryUrl {
`IScmRepositoryUrl` -- this one is not yet parsed.

2023-04-06 09:46 UTC, patrikk0123 commented on src/utils/utils.ts
> + * @returns parsedUrl contains parsedUrl and displayName
`Object containing parsed URL and display name representing URL`

2023-04-06 09:46 UTC, patrikk0123 commented on src/utils/utils.ts
> + * @returns  Object contains url and the base of the external url
`Object containing parsed URL and display name representing URL`

2023-04-06 09:46 UTC, patrikk0123 commented on src/utils/utils.ts
> + * @param externalUrl - The externalUrl to be parsed
`url`

2023-04-06 09:46 UTC, patrikk0123 commented on src/utils/utils.ts
> + * @param internalUrl - The internalUrl to be parsed
`url`

2023-04-06 13:03 UTC, DnsZhou commented on src/components/ScmRepositoryUrl/ScmRepositoryUrl.tsx
> +    : parseExternalScmRepositoryUrl({ url: originalUrl });
using different repository objects was suggested by Martin, @matedo1 wdyt?

2023-04-06 13:28 UTC, matedo1 requested changes

2023-04-06 17:01 UTC, matedo1 requested changes
Some last small changes

2023-04-10 22:16 UTC, DnsZhou commented
@matedo1  ready for review again

2023-04-11 08:00 UTC, matedo1 requested changes

2023-04-11 08:00 UTC, matedo1 commented on src/utils/urlParseHelper.ts
> + * 2) object containing parsed URL and display name representing URL
`Object containing scmRepository URL, parsed URL and display name representing URL`

2023-04-11 11:54 UTC, DnsZhou commented
@matedo1  ready for review, Thanks

2023-04-11 11:55 UTC, matedo1 approved these changes

2023-04-11 12:41 UTC, merged