[NCL-7768] Implement Product Milestone-Artifact table
project-ncl/pnc-web-ui-react pull request #195
Opened 2023-04-10 15:50 UTC by patrikk0123

2023-04-18 14:23 UTC, matedo1 requested changes

2023-04-21 18:40 UTC, matedo1 commented
Hi @patrikk0123 , service container changes are merged (#203), feel free to rebase this PR on top of it.

2023-04-24 08:25 UTC, matedo1 commented on src/services/productMilestoneApi.tsx
> + * * @param serviceData - object containing:
done

2023-04-24 08:25 UTC, matedo1 commented on src/components/ServiceContainers/ServiceContainerLoading.tsx
> +  initLoadingState?: boolean;
done

2023-04-24 08:26 UTC, matedo1 commented on src/components/ProductMilestoneComparisonTablePage/ProductMilestoneComparisonTablePage.tsx
> +          Table lists Artifacts and their versions in selected Product Milestones. Product Milestones can be removed from the
@patrikk0123 @janinko , what's the current state?

2023-04-24 08:27 UTC, matedo1 commented on src/components/ProductMilestoneComparisonTable/ProductMilestoneComparisonTable.tsx
> +            onSelect={(_, entity?: any) => {
done

2023-04-24 08:27 UTC, matedo1 commented on src/components/ProductMilestoneComparisonTable/ProductMilestoneComparisonTable.tsx
> +            onSelect={(_, entity?: any) => {
done

2023-04-24 08:27 UTC, matedo1 commented on src/components/ProductMilestoneComparisonTable/ProductMilestoneComparisonTable.tsx
> +            onSelect={(_, entity?: any) => setSelectedProductMilestone(entity)}
done

2023-04-24 08:28 UTC, matedo1 commented on src/components/ProductMilestoneComparisonTablePage/ProductMilestoneComparisonTablePage.tsx
> +interface IProductMilestoneComparisonTablePageProps {
done

2023-04-24 08:28 UTC, matedo1 commented on src/services/productMilestoneApi.tsx
> +export const getProductMilestoneComparisonTable = (
done

2023-04-24 08:29 UTC, matedo1 commented on src/services/productMilestoneApi.tsx
> +  return mockClient.getHttpClient().post<any>(`/product-milestone-comparison-table`, data, requestConfig);
done

2023-04-24 08:31 UTC, matedo1 commented on src/components/ProductMilestoneComparisonTable/ProductMilestoneComparisonTable.tsx
> +              Fetch
done

2023-04-24 08:31 UTC, matedo1 commented on src/common/constants.ts
> +  productMilestoneComparisonTable: 'Product Milestone Comparison',
done

2023-04-24 08:32 UTC, matedo1 commented on src/components/ProductMilestoneComparisonTable/ProductMilestoneComparisonTable.tsx
> +    (milestoneColumn: any) => selectedProductMilestone?.id === milestoneColumn.id
Why also type `IProductMilestoneColumn` was not added?

2023-04-24 08:33 UTC, matedo1 commented on src/components/SearchSelect/SearchSelect.tsx
>    const [currentData, setCurrentData] = useState<any[]>([]);
done

2023-04-24 08:58 UTC, matedo1 commented on src/components/ProductMilestoneComparisonTable/ProductMilestoneComparisonTable.tsx
> +              isAriaDisabled={
ok, I found documentation covering this behavior, please add following link as comment: `https://www.patternfly.org/v4/components/tooltip/accessibility/#additional-considerations`

2023-04-24 09:07 UTC, patrikk0123 commented on src/components/ProductMilestoneComparisonTable/ProductMilestoneComparisonTable.tsx
> +    (milestoneColumn: any) => selectedProductMilestone?.id === milestoneColumn.id
It's not needed for `.some` or '.map` if the collection has type determined.

2023-04-24 11:18 UTC, matedo1 commented on src/components/ProductMilestoneComparisonTable/ProductMilestoneComparisonTable.tsx
> +    (milestoneColumn: any) => selectedProductMilestone?.id === milestoneColumn.id
`any` type was removed, done

2023-04-24 11:26 UTC, matedo1 approved these changes

2023-04-26 09:12 UTC, matedo1 approved these changes

2023-04-26 09:19 UTC, merged