[NCL-7223] Implement Product Releases list
project-ncl/pnc-web-ui-react pull request #226
Opened 2023-05-17 09:28 UTC by patrikk0123

2023-05-29 17:29 UTC, DnsZhou requested changes
Hi @patrikk0123 , Thanks for the work and just some minor changes over the UI. Thanks.

2023-05-29 17:29 UTC, DnsZhou commented on src/components/ProductVersionReleasesList/ProductVersionReleasesList.tsx
> +                      ]}
We can use `Edit Release` and `Delete Release` instead of a longer version, which keeps the same with our angular JS UI

2023-05-30 08:58 UTC, matedo1 commented on src/components/ProductVersionReleasesList/ProductVersionReleasesList.tsx
> +                <Th width={25}>Name</Th>
Use `Version` instead of `Name` (the same is applied on Milestones page)

2023-06-24 01:50 UTC, DnsZhou commented
lgtm. Thanks

2023-06-29 08:41 UTC, merged