[NCL-7777] Fix Content jumping issue
project-ncl/pnc-web-ui-react pull request #239
Opened 2023-06-24 01:43 UTC by DnsZhou

2023-06-26 10:26 UTC, matedo1 reviewed
See jira comments

2023-06-30 01:17 UTC, DnsZhou commented
H @matedo1 , changes applied and see jira for latest gifs.

2023-07-07 08:49 UTC, matedo1 commented
Hi @patrikk0123 , could you please finish code review for this one? 

@DnsZhou could you please squas your commits into one or two? Nine commits seem to be a little bit confusing in this case as finally just a few simply lines were modified.

2023-07-10 10:59 UTC, patrikk0123 reviewed
Some code comments.

2023-07-10 10:59 UTC, patrikk0123 commented on src/components/Tabs/Tabs.tsx
> +const tabsMinHeight: React.CSSProperties = { minHeight: '45px' };
Move it into `Tabs.module.css` file (class tabs).

2023-07-10 10:59 UTC, patrikk0123 commented on src/components/ProductMilestonePages/ProductMilestonePages.tsx
> +const labelMinWidth: React.CSSProperties = { minWidth: '20px', minHeight: '15px' };
`labelStyles`

2023-07-10 13:15 UTC, DnsZhou commented
I have force-pushed the changes into one commit and extracted the component. See jira NCL-7777 for gifs that fixed the error.

2023-07-10 14:15 UTC, matedo1 requested changes

2023-07-10 14:15 UTC, matedo1 commented on src/components/ProductMilestonePages/ProductMilestonePages.tsx
> +        <TabsLabel serviceContainer={serviceContainerArtifacts} tooltip={'Total Count'} title={'Delivered Artifacts Count'}>
Using 
```tsx
<TabsLabel serviceContainer={serviceContainerArtifacts} title="Delivered Artifacts Count">
``` 
etc. should be enough?

2023-07-10 14:15 UTC, matedo1 commented on src/components/Tabs/Tabs.module.css
> +.page-section-tabs :global(.pf-c-label) {
I can see you decided to implement `TabsLabel` component I proposed, in this case you should move also part of the related stylesheets (nested ones) into new file `TabsLabel.module.css`:

```css
.tabs-label :global(.pf-c-label) { /* ... */ }

/* etc */
```

2023-07-10 14:15 UTC, matedo1 commented on src/components/Tabs/TabsLabel.tsx
> +  tooltip: string;
remove, `title` is enough

2023-07-11 09:23 UTC, matedo1 requested changes

2023-07-11 12:25 UTC, DnsZhou commented on src/components/Tabs/TabsLabel.tsx
> +      <Label>
added back

2023-07-11 13:28 UTC, patrikk0123 approved these changes
I approve, just please squash commits.

2023-07-11 13:56 UTC, DnsZhou commented
Hi @patrikk0123 , there are only 3 commits now, it was already squashed in the last force push. wold that be okay?

2023-07-11 14:24 UTC, patrikk0123 commented
> Hi @patrikk0123 , there are only 3 commits now, it was already squashed in the last force push. wold that be okay?

Count does not matter that much, but commits contradict themselves - add tooltip; bring tooltip back.
The final branch before merging should really be divided based on content and historical changes as the branch was developed need to be hidden by squashing.

2023-07-11 23:20 UTC, DnsZhou commented
squashed and merged. Thanks @patrikk0123

2023-07-11 23:22 UTC, merged