[NCL-6755] Create first unit test for Project List
project-ncl/pnc-web-ui-react pull request #26
Opened 2021-11-15 03:37 UTC by DnsZhou

2021-11-15 13:52 UTC, matedo1 requested changes

2021-11-15 13:52 UTC, matedo1 commented on src/components/ProjectsList/__tests__/ProjectsList.test.tsx
> +describe('display project list page', () => {
I think `'ProjectList component'` description is more appropriate, at least `page` should not be there as it's just component in our terminology

2021-11-15 13:52 UTC, matedo1 commented on src/components/ProjectsList/__tests__/ProjectsList.test.tsx
> +  afterEach(async () => {});
is this neccessary if it's empty?

2021-11-15 13:52 UTC, matedo1 commented on src/components/ProjectsList/__tests__/ProjectsList.test.tsx
> +  test('renders ProjectList to have the right data and', () => {
is description valid? `and` seems to be added just by mistake?

2021-11-15 22:14 UTC, DnsZhou commented
Hi @matedo1 , all issues were fixed accordingly, also the snapshot test was integrated as well.

2021-11-16 21:05 UTC, matedo1 approved these changes
Thanks!

2021-11-18 00:44 UTC, closed without merging