[NCL-7219] Implement Artifact Product Milestones page
project-ncl/pnc-web-ui-react pull request #265
Opened 2023-07-27 09:35 UTC by patrikk0123

Product Milestone and Release labels are missing because of the weird data format returned by REST API.

2023-07-31 12:07 UTC, matedo1 requested changes
Thanks for your changes!

Naming conventions:

UI: `Milestone`, `Release`
Code: `productMilestone`, `productRelease`, `artifactProductMilestoneRelease`

2023-07-31 12:07 UTC, matedo1 commented on src/components/ProductMilestoneInfoList/ProductMilestoneInfoList.tsx
> +                <Th width={15}>{milestoneInfoEntityAttributes.releaseVersion.title}</Th>
I would use `Release {productReleaseEntityAttributes.version.title}`.

Apply the same on other places too.

2023-07-31 12:07 UTC, matedo1 commented on src/components/ArtifactProductMilestonesPage/ArtifactProductMilestonesPage.tsx
> +  const serviceContainerProductMilestoneInfo = useServiceContainer(artifactApi.getProductMilestones);
`serviceContainerArtifactProductMilestoneRelease`

2023-07-31 12:37 UTC, patrikk0123 commented on src/common/milestoneInfoEntityAttributes.ts
> +  releaseVersion: {
This has to be consistent with the property returned by the backend.

2023-07-31 12:42 UTC, matedo1 commented on src/common/milestoneInfoEntityAttributes.ts
> +  releaseVersion: {
Then let's reuse just some specific properties like `title` (or just part of it)

2023-08-03 10:20 UTC, matedo1 commented on src/common/artfactProductMilestoneReleaseEntityAttributes.ts
> +export const artfactProductMilestoneReleaseEntityAttributes = {
typo mistake `artfact` instead of `artifact`

2023-08-03 10:21 UTC, matedo1 commented on src/components/ProductMilestoneInfoList/ProductMilestoneInfoList.tsx
> +export const ProductMilestoneInfoList = ({
done

2023-08-03 10:22 UTC, matedo1 commented on src/common/milestoneInfoEntityAttributes.ts
> +  releaseVersion: {
done

2023-08-03 10:22 UTC, matedo1 commented on src/AppRoutes.tsx
> +        <Route path="milestones" element={<ArtifactProductMilestonesPage />} />
done

2023-08-03 10:23 UTC, matedo1 commented on src/components/ArtifactPages/ArtifactPages.tsx
> -      <TabsItem url="milestones">Milestones and Releases</TabsItem>
done

2023-08-03 10:23 UTC, matedo1 commented on src/components/ProductMilestoneInfoList/ProductMilestoneInfoList.tsx
> +              {serviceContainerProductMilestoneInfo.data?.content.map((milestoneInfo: MilestoneInfo, rowIndex: number) => (
done

2023-08-03 10:24 UTC, matedo1 commented on src/components/ProductMilestoneInfoList/ProductMilestoneInfoList.tsx
> +                <Th width={15}>{milestoneInfoEntityAttributes.releaseVersion.title}</Th>
done (corrected version)

2023-08-03 10:25 UTC, matedo1 commented on src/components/ArtifactProductMilestonesPage/ArtifactProductMilestonesPage.tsx
> +  const serviceContainerProductMilestoneInfo = useServiceContainer(artifactApi.getProductMilestones);
done (corrected version)

2023-08-03 11:18 UTC, matedo1 requested changes
Also commit message could be changed to included "Releases" part.

Thanks!

2023-08-03 11:18 UTC, matedo1 commented on src/components/ProductVersionReleasesList/ProductVersionReleasesList.tsx
> +                  info={{
@DnsZhou already started to use our tooltip implementation, see https://github.com/project-ncl/pnc-web-ui-react/blob/main/src/components/ScmRepositoriesList/ScmRepositoriesList.tsx#L80

We should be using the same also here. The advantage is that the same tooltip design (icon, tooltip itself) is used also on other pages like detail page.

Apply the same on all other places.

2023-08-03 11:18 UTC, matedo1 commented on src/components/ArtifactProductMilestonesReleasesList/ArtifactProductMilestonesReleasesList.tsx
> +                  info={{
See other comment.

2023-08-03 11:18 UTC, matedo1 commented on src/components/ProductVersionReleasesList/ProductVersionReleasesList.tsx
> +                  info={{
Anyway, thanks for applying given change also on this place!

2023-08-03 13:32 UTC, matedo1 requested changes

2023-08-03 13:32 UTC, matedo1 commented on src/components/ArtifactProductMilestonesReleasesList/ArtifactProductMilestonesReleasesList.tsx
> +                <Th width={20}>Product {artfactProductMilestoneReleaseEntityAttributes.productName.title}</Th>
In the end `Product` prefix needs to be moved into `artfactProductMilestoneReleaseEntityAttributes` to make sure both filtering and column header titles are matching.

2023-08-03 15:14 UTC, patrikk0123 commented on src/services/artifactApi.ts
> + * Gets list of Product Milestones that produced or consumed an Artifact.
Artifact itself is unknown and service is generic (usable for any Artifact entity), so I will stick to the`an` article. Besides, we use `a` or `an` articles in other TSDocs of service functions.

2023-08-03 15:18 UTC, patrikk0123 commented
@DnsZhou
1) Jira was already created for the issue (NCL-8062).

2023-08-03 18:07 UTC, matedo1 commented on src/common/artfactProductMilestoneReleaseEntityAttributes.ts
> +export const artfactProductMilestoneReleaseEntityAttributes = {
done

2023-08-03 18:07 UTC, matedo1 commented on src/components/ArtifactProductMilestonesReleasesList/ArtifactProductMilestonesReleasesList.tsx
> +                  info={{
done

2023-08-03 18:07 UTC, matedo1 commented on src/components/ArtifactProductMilestonesReleasesList/ArtifactProductMilestonesReleasesList.tsx
> +                <Th width={20}>Product {artfactProductMilestoneReleaseEntityAttributes.productName.title}</Th>
done

2023-08-03 18:15 UTC, matedo1 approved these changes
Some optional changes, otherwise approved. Thanks

2023-08-03 18:15 UTC, matedo1 commented on src/common/artifactProductMilestoneReleaseEntityAttributes.ts
> +    title: productVersionEntityAttributes.version.title,
Optionally: `Product ${productVersionEntityAttributes.version.title}`

2023-08-03 18:15 UTC, matedo1 commented on src/common/artifactProductMilestoneReleaseEntityAttributes.ts
> +    title: productMilestoneEntityAttributes.endDate.title,
Optionally: `Milestone ${productMilestoneEntityAttributes.endDate.title}`

2023-08-04 02:26 UTC, DnsZhou approved these changes

2023-08-07 07:09 UTC, merged