[NCL-7699] Rework useForm hook
project-ncl/pnc-web-ui-react pull request #279
Opened 2023-08-14 13:03 UTC by patrikk0123

2023-08-31 11:53 UTC, matedo1 requested changes
Thanks for looking into this and raising this PR! 

One thing we need to keep in mind is that spread operator creates shallow copies for nested content. We need to be more careful.

[optional] Methods itself could contain more inner comments, I think other guys would appreciate it. I would leave it up to you to choose some places.

It would be nice to see also some working example where for example `register<boolean>` is used.

2023-08-31 12:22 UTC, patrikk0123 commented on src/hooks/useNewForm.ts
> +type OnSubmitCallback = (data: IFieldValues) => void;
We don't put `T` prefix on function notation types.

2023-08-31 12:22 UTC, patrikk0123 commented on src/hooks/useNewForm.ts
> +type OnSubmitFunction = () => void;
We don't put `T` prefix on function notation types.

2023-08-31 12:22 UTC, patrikk0123 commented on src/hooks/useNewForm.ts
> +type OnChangeFunction<T> = (value: T) => void;
We don't put `T` prefix on function notation types.

2023-08-31 12:29 UTC, matedo1 commented
Hi @DnsZhou , please can you get familiar with this changes? Possibly also review could be useful.

2023-08-31 12:39 UTC, patrikk0123 commented on src/hooks/useNewForm.ts
> +    if (typeof value === 'string') {
When field has value of different type.

2023-08-31 12:41 UTC, patrikk0123 commented on src/hooks/useNewForm.ts
> +export type TFieldConfig<T> = Omit<IField<T>, 'value' | 'errorMessages' | 'state'>;
It might be needed.

2023-08-31 12:41 UTC, patrikk0123 commented on src/hooks/useNewForm.ts
> +export type TFieldConfig<T> = Omit<IField<T>, 'value' | 'errorMessages' | 'state'>;
It might be needed.

2023-08-31 15:19 UTC, matedo1 commented on src/components/FormInput/FormInput.tsx
> +export const FormInput = <T,>({ value, onChange, validated, render }: IFormInputProps<T>) => {
done

2023-08-31 15:19 UTC, matedo1 commented on src/hooks/useNewForm.ts
> + *
done

2023-08-31 15:19 UTC, matedo1 commented on src/hooks/useNewForm.ts
> +  const getFieldValue = (fieldName: string) => {
done

2023-08-31 15:19 UTC, matedo1 commented on src/hooks/useNewForm.ts
> + *  - register         - function registering an input and returning its value, state and on-change function
done

2023-08-31 15:20 UTC, matedo1 commented on src/hooks/useNewForm.ts
> +    return { value: fields[fieldName]?.value, onChange: handleChange<T>(fieldName), validated: fields[fieldName]?.state };
done

2023-08-31 15:20 UTC, matedo1 commented on src/hooks/useNewForm.ts
> +  const getNewField = <T>(field: IField<T>, value: T): IField<T> => {
done

2023-08-31 15:21 UTC, matedo1 commented on src/hooks/useNewForm.ts
> +      setHasFormChanged(false);
done

2023-08-31 15:21 UTC, matedo1 commented on src/hooks/useNewForm.ts
> +    const newField: IField<T> = { ...field };
done

2023-08-31 15:21 UTC, matedo1 commented on src/hooks/useNewForm.ts
> +        fieldsCopy[fieldName].state = 'default';
done, it will be tested on master deployment

2023-08-31 15:32 UTC, matedo1 approved these changes
Thanks for fixing it quickly, feel free to merge it.

2023-09-04 00:53 UTC, DnsZhou approved these changes
Code looks good and verified from my local side, Thanks!

2023-09-04 10:21 UTC, merged