[NCL-8167] Implement Group Configs list edit page
project-ncl/pnc-web-ui-react pull request #319
Opened 2023-10-04 09:09 UTC by patrikk0123

2023-10-25 08:29 UTC, matedo1 requested changes

2023-10-25 08:29 UTC, matedo1 commented on src/services/groupConfigApi.ts
> +  // TODO: extend request config with the helper function
This should be rebased on top of https://github.com/project-ncl/pnc-web-ui-react/pull/328 which is already merged

2023-10-25 08:36 UTC, matedo1 commented
Hi @jomrazek , can you please do a code-review for this one? 

Very similar feature was already implemented here https://github.com/project-ncl/pnc-web-ui-react/pull/312 (see Product Version > Build Configs (tab) > Edit list), this PR is re-using the same code, but Patrik generalised for both entities - Group Config and Build Config

Then he implemented some Group Config specific part on top of it.

In this case React UI is very different from the AngularJS UI, as React UI adds full pagination support on all places.

2023-10-27 08:43 UTC, jomrazek commented
Apart Martin's comment about using new extendRequestConfig, it looks ok to me.

2023-10-31 11:44 UTC, merged