[NCL-8117] Implement Build Brew Push page
project-ncl/pnc-web-ui-react pull request #333
Opened 2023-11-01 13:17 UTC by patrikk0123

2023-11-01 13:18 UTC, patrikk0123 reviewed
Live log was separated to a Jira NCL-8268, since the websockets still were not integrated.

2023-11-07 14:09 UTC, DnsZhou requested changes
Hi @patrikk0123 , the code mostly looks good but I found that when I hit the `push to brew` button on the right top of the brew push page and proceed, the `Open brew push details` button does not work as expected. I have to click close and refresh button to see the result. is this an expected behaviour or we can improve it? ideally it should be refreshed automatically when brew push was proceeded.

2023-11-07 14:47 UTC, matedo1 commented
Hi @DnsZhou we keep it open and display status (pending, success, error) there. Once finished, user can decide what action should be performed next (refresh, go to the detail + refresh, etc). Different modal windows can have different action, but we want to keep the behavior the same.

2023-11-07 15:53 UTC, DnsZhou approved these changes

2023-11-08 09:21 UTC, merged