[NCL-7207] Implement Insert / Remove dependencies functionality for Build Config
project-ncl/pnc-web-ui-react pull request #355
Opened 2023-12-14 16:37 UTC by patrikk0123

2024-01-11 08:33 UTC, patrikk0123 commented on src/components/BuildConfigDependenciesEditPage/BuildConfigDependenciesEditPage.tsx
> +  const serviceContainerBuildConfigEdit = useServiceContainer(buildConfigApi.editBuildConfig, 0);
I would use patch, but REST API supports only put in this case.

2024-01-11 09:26 UTC, matedo1 commented on src/components/BuildConfigDependenciesEditPage/BuildConfigDependenciesEditPage.tsx
> +  const serviceContainerBuildConfigEdit = useServiceContainer(buildConfigApi.editBuildConfig, 0);
We agreed to investigate it more deeply, according to swagger it should be supported, possibly two follow up jiras will be created (one for backend to fix it, one for UI to integrate it)

2024-01-15 16:10 UTC, patrikk0123 commented on src/components/BuildConfigDependenciesEditPage/BuildConfigDependenciesEditPage.tsx
> +  const serviceContainerBuildConfigEdit = useServiceContainer(buildConfigApi.editBuildConfig, 0);
It was my fault, I was sending the backend the wrong data.

2024-01-16 14:42 UTC, matedo1 commented
I tested it locally and write jira comment with questions

2024-01-17 14:20 UTC, matedo1 commented
I tested it locally and write jira comment with issues

2024-01-17 14:21 UTC, matedo1 requested changes
I tested it locally and write jira comment with issues

2024-01-17 15:58 UTC, matedo1 requested changes
I successfully tested it locally. Thanks

2024-01-17 15:58 UTC, matedo1 commented on src/components/BuildConfigDependenciesEditPage/BuildConfigDependenciesEditPage.tsx
> +import { ConfigsAddList } from 'components/ProductVersionBuildConfigsEditPage/ConfigsAddList';
ping

2024-01-17 15:58 UTC, matedo1 commented on src/components/ProductVersionBuildConfigsEditPage/ConfigsAddList.tsx
> +      (!buildConfigToExclude || !isBuildConfig(config) || config.id !== buildConfigToExclude) &&
Please create some named variable explaining individual condition groups, or at least some TSDocs would be helpful. Now it's very hard to maintain.

2024-01-22 10:45 UTC, patrikk0123 commented on src/components/BuildConfigDependenciesEditPage/BuildConfigDependenciesEditPage.tsx
> +import { ConfigsAddList } from 'components/ProductVersionBuildConfigsEditPage/ConfigsAddList';
I don't know what you mean by this comment.

2024-01-23 12:22 UTC, matedo1 commented
Again, I successfully tested it locally. Thanks

2024-01-23 12:23 UTC, matedo1 approved these changes

2024-01-23 12:25 UTC, merged