[NCL-7207] Build Config create/edit page - repository section
project-ncl/pnc-web-ui-react pull request #369
Opened 2024-01-24 13:37 UTC by patrikk0123

2024-01-30 13:24 UTC, matedo1 requested changes

2024-01-30 13:24 UTC, matedo1 commented on src/components/BuildConfigCreateEditPage/BuildConfigCreateEditPage.tsx
> +            label={`${buildConfigEntityAttributes.scmRepository.title} URL`}
Please share as much as possible content like this with SCM Repositories create page - for example all title and tooltip attributes. 

The same as valid for other common parts like validation, "blue box" displaying information whether repository is already synced or not (let's export it as separated component). Please create follow-up jiras to apply required changes on SCM Repositories create page.

The goal is to this section and SCM Repositories create page synced as much as possible.

2024-01-30 13:24 UTC, matedo1 commented on src/components/BuildConfigCreateEditPage/BuildConfigCreateEditPage.tsx
> +                  isDisabled={!!selectedScmRepository}
Is it possible to display the reason why it's disabled?

2024-01-30 18:32 UTC, matedo1 approved these changes
Did you create new jira to integrate `ScmRepositoryUrlAlert` on SCM Repositories create page?

2024-01-31 09:24 UTC, patrikk0123 commented
> ScmRepositoryUrlAlert

NCL-8383

2024-01-31 09:24 UTC, merged