[NCL-8483] Implement alternative solution for Build Script editor
project-ncl/pnc-web-ui-react pull request #409
Opened 2024-03-01 13:56 UTC by patrikk0123

2024-03-01 14:32 UTC, matedo1 requested changes
Just minor styling changes, thanks!

2024-03-01 14:32 UTC, matedo1 commented on src/components/CodeEditor/CodeEditor.module.css
> +  vertical-align: center;
This is invalid property value

2024-03-01 14:32 UTC, matedo1 commented on src/components/CodeEditor/CodeEditor.module.css
> +  position: absolute;
Add `top: 1px` to align it more properly with right side textarea content.

2024-03-01 14:32 UTC, matedo1 commented on src/components/CodeEditor/CodeEditor.module.css
> +  overflow-y: hidden;
I think marked lines 20-23 can be removed.

2024-03-01 14:32 UTC, matedo1 commented on src/components/CodeEditor/CodeEditor.module.css
> +  font-weight: 400;
I think this can be remove too.

2024-03-01 14:32 UTC, matedo1 commented on src/components/CodeEditor/CodeEditor.module.css
> +  width: calc(100% - 4rem);
This is not applied, it should not be needed anyway.

2024-03-04 10:01 UTC, patrikk0123 commented on src/components/CodeEditor/CodeEditor.module.css
> +  vertical-align: center;
leftover by accident

2024-03-04 11:54 UTC, matedo1 approved these changes

2024-03-04 12:07 UTC, merged