[NCL-8499] Fix Username component truncating
project-ncl/pnc-web-ui-react pull request #424
Opened 2024-03-12 15:34 UTC by patrikk0123

2024-03-12 16:46 UTC, matedo1 requested changes

2024-03-12 16:46 UTC, matedo1 commented on src/components/Username/Username.tsx
> +  return resultText.length !== text.length ? (
This will display `..` automatically for all usernames containing `service-account-`, for example `service-account-a` will be displayed as `(SA) a..`

2024-03-12 16:46 UTC, matedo1 commented on src/components/Username/Username.tsx
> +  // prettify the result
[optional] `return truncatedUsername.replace(/-$/, '');` would be enough, or even more generalized regex `/-+$/`, so finally:

```ts
const truncateUsername = (username: string, length: number): string => username.replace(serviceAccountKeyword, '').substring(0, length).replace(/-+$/, '');
```

2024-03-12 16:46 UTC, matedo1 commented on src/components/Username/Username.tsx
> +        <>..</>
[optional] `<>` is not needed

2024-03-12 16:46 UTC, matedo1 commented on src/components/Username/Username.tsx
> +const serviceAccountKeyword = 'service-account-';
[optional] If it's constant, then uppercase should be considered.

2024-03-13 11:55 UTC, patrikk0123 commented on src/components/Username/Username.tsx
> +        <>..</>
No longer relevant (code changed).

2024-03-13 14:24 UTC, merged