[NCL-8506] Provide Build Log link on Status Icon
project-ncl/pnc-web-ui-react pull request #463
Opened 2024-04-11 12:17 UTC by patrikk0123

2024-04-11 12:35 UTC, matedo1 requested changes

2024-04-11 12:35 UTC, matedo1 commented on src/components/BuildStatusIcon/BuildStatusIcon.tsx
> +  const buildLogLink = selectedIconData.failed ? `/builds/${build.id}/alignment-log` : `/builds/${build.id}/build-log`;
@jomrazek is this condition valid?

2024-04-11 12:35 UTC, matedo1 commented on src/components/BuildStatusIcon/BuildStatusIcon.module.css
> +  display: block;
`display: inline-block`

2024-04-11 12:53 UTC, patrikk0123 commented on src/components/BuildStatusIcon/BuildStatusIcon.module.css
> +  display: block;
no, it has  to be block

2024-04-15 10:41 UTC, patrikk0123 commented on src/components/BuildStatusIcon/BuildStatusIcon.tsx
> +  const buildLogLink = selectedIconData.failed ? `/builds/${build.id}/alignment-log` : `/builds/${build.id}/build-log`;
probably some other condition would suit better, I put there some just as proof of concept

2024-04-15 16:53 UTC, matedo1 commented on src/components/BuildStatusIcon/BuildStatusIcon.tsx
> +  const buildLogLink = selectedIconData.failed ? `/builds/${build.id}/alignment-log` : `/builds/${build.id}/build-log`;
We discussed another approach on PM.

2024-04-17 07:14 UTC, matedo1 approved these changes
Approved, just minor comments

2024-04-17 07:14 UTC, matedo1 commented on src/components/BuildStatusIcon/BuildStatusIcon.tsx
> +interface IBuildLogLink {
`IBuildLogLinkProps`

2024-04-17 07:14 UTC, matedo1 commented on src/components/BuildStatusIcon/BuildStatusIcon.tsx
> +    <TooltipWrapper tooltip={<span>{buildStatusData[build.status!].tooltip}. Click to open the log</span>}>
`<span>` should not be needed

2024-04-18 08:05 UTC, merged