[NCL-8755] Show SSH details for PNC admins
project-ncl/pnc-web-ui-react pull request #555
Opened 2024-07-24 01:10 UTC by DnsZhou

This is the new PR in replacement of https://github.com/project-ncl/pnc-web-ui-react/pull/552.

2024-07-24 01:13 UTC, DnsZhou commented
Due to missing backend support(see NCL-8756), 401 error is expected for PNC users on build log details page after this PR get merged. cc @matedo1 to confirm if we still want to proceed.

2024-07-24 08:15 UTC, patrikk0123 requested changes

2024-07-24 08:15 UTC, patrikk0123 commented on src/components/BuildLogPage/BuildLogPage.tsx
> +    <SshCredentialsButton
The SSH credentials button should no longer be on the Build log page, but rather on top bar of Build pages

2024-07-29 11:47 UTC, matedo1 commented
Hi @DnsZhou , I've noticed jira number (PR title, commit message) is wrong

2024-08-01 10:29 UTC, closed without merging