[NCL-8826] Clear Brew Push legacy log when trigger new Brew Push
project-ncl/pnc-web-ui-react pull request #599
Opened 2024-10-31 15:38 UTC by DnsZhou

2024-10-31 17:10 UTC, matedo1 commented
I would like to try a little bit different approach, especially `setResetLogTrigger()` related logic should be avoided. What about implement `addOnOpenListener()` and clear, or just force page reload when new WebSocket channel is open? Let's discuss additional details on PM.

2024-10-31 21:57 UTC, DnsZhou commented
@matedo1  We first need to know when the new WS channel should be opened, this is a chicken-egg problem. 

New ws channel opens with the initialization of useBifrostWebSocketEffect when we load buildBrewPushPage(and other pages with log viewer that contains useBifrostWebSocketEffect).

We anyway need to pass a message to buildBrewPush page so that it knows a new brew push is triggered, then, either clear the buffer or start a new ws channel will both do the job. I think clear the buffer is enough.

2024-11-01 06:50 UTC, matedo1 commented
I understand your worries, but log should ideally reseted always once new WebSocket is open = once old WebSocket connection is close. I've just tested it locally and it seems it's working well. I slightly improved it and I am using `addOnCloseListener()` listeners instead, then log reset is performed (page refresh is problematic, let's avoid it).

2024-11-04 12:59 UTC, DnsZhou commented
Hi @matedo1 , feel free to review this version. I also fixed the empty web socket problem for brew push log(this existed before my change for clearing the log, it was caused by initialing ws too early before brew push id was on hand )

2024-11-04 14:02 UTC, matedo1 requested changes

2024-11-04 14:02 UTC, matedo1 commented on src/components/BuildBrewPushPage/BuildBrewPushPage.tsx
> +  const handleOnClose = useCallback(() => {
Is it needed to use `useCallback` again? I think `resetLogBuffer` is already memoized.

2024-11-04 14:02 UTC, matedo1 commented on src/hooks/useBifrostWebSocketEffect.ts
> +  onClose?: () => void;
Please add some TSDoc

2024-11-04 16:50 UTC, matedo1 approved these changes

2024-11-04 17:45 UTC, merged