[NCL-6954] Add Build Start Button Group
project-ncl/pnc-web-ui-react pull request #63
Opened 2022-04-24 21:22 UTC by DnsZhou

2022-04-27 09:49 UTC, matedo1 requested changes
Thanks, just minor changes

2022-04-27 09:49 UTC, matedo1 commented on src/components/BuildStartButton/BuildStartButton.tsx
> +                <span className={'pnc-info-icon'}>
why is not using just `"pnc-info-icon"` enough? (the same for other cases)

2022-04-27 09:49 UTC, matedo1 commented on src/components/BuildStartButton/BuildStartButton.tsx
> +  const [isTempBuild, setIsTempBuild] = useState(false);
add missing types if possible, for example: `useState<boolean>(false)` (the same for all other cases)

2022-04-28 12:51 UTC, DnsZhou commented on src/components/BuildStartButton/BuildStartButton.tsx
> +        alignments={{ sm: 'right', md: 'right', lg: 'right' }}
https://github.com/project-ncl/pnc-web-ui-react/blob/main/src/components/ProjectCreateEditPage/ProjectCreateEditPage.tsx#L31

2022-04-28 12:52 UTC, DnsZhou commented on src/components/BuildStartButton/BuildStartButton.module.css
> +  display: block;
will remove it

2022-04-29 16:15 UTC, DnsZhou commented
updated and ready for review @matedo1

2022-05-02 08:11 UTC, matedo1 approved these changes

2022-05-03 12:47 UTC, merged