[NCL-7256] Keep UI partially working even if KeyCloak is not available
project-ncl/pnc-web-ui-react pull request #84
Opened 2022-08-10 09:12 UTC by patrikk0123

2022-08-10 09:22 UTC, matedo1 commented
Hi @jomrazek , could you please do a review for @patrikk0123 ?

2022-08-11 12:02 UTC, jomrazek reviewed
looks ok to me

2022-08-11 14:57 UTC, matedo1 requested changes

2022-08-11 14:57 UTC, matedo1 commented on src/AppRoutes.tsx
> +  title?: string;
I would be strict in this case for now, let's remove `?` character

2022-08-11 14:57 UTC, matedo1 commented on src/AppRoutes.tsx
> +    <Route path="*" element={<ErrorPage errorDescription="The requested resource could not be found."></ErrorPage>} />
I would use also `title` attribute `Page not found`, but define it inside https://github.com/project-ncl/pnc-web-ui-react/blob/main/src/utils/PageTitles.ts like `pageNotFound`

2022-08-11 14:57 UTC, matedo1 commented on src/components/ErrorPage/ErrorPage.tsx
> +  pageTitle?: string;
I would be strict also in this case, let's remove `?`, then also default values bellow will be removed

2022-08-11 14:57 UTC, matedo1 commented on src/components/ErrorPage/ErrorPage.module.css
> +  margin-top: 15px;
for generic margins, paddings, etc, we use so called generics (see index.css), let's use `m-t-15: 15px` and remove this css module

2022-08-11 14:57 UTC, matedo1 commented on src/AppRoutes.tsx
> +          <ProtectedRoute title="Create Project">
let's define all titles inside https://github.com/project-ncl/pnc-web-ui-react/blob/main/src/utils/PageTitles.ts

2022-08-17 12:25 UTC, jomrazek commented on src/services/pncClient.ts
> +      if (keycloakService.isKeycloakAvailable && keycloakService.isAuthenticated()) {
if we care just about true or false, can't we move isKeycloakAvailable check into service? Same for getUser and hasRealmRole in appLayout? Seems like we would need to do this check in all classes when using those methods while they can return false from service when we don't need to differentiate the failure point.

2022-08-17 13:25 UTC, closed without merging

2022-08-17 14:25 UTC, patrikk0123 commented
Changes had to be done, continuation here:
https://github.com/project-ncl/pnc-web-ui-react/pull/87