[NCL-7000] Implement PATCH method for Project update
project-ncl/pnc-web-ui-react pull request #90
Opened 2022-08-29 10:36 UTC by patrikk0123

2022-09-06 08:32 UTC, jomrazek reviewed
Looks ok to me and works ok, we just talked with Patrik about returning back to project detail page from update page after update is done.

2022-09-13 14:09 UTC, matedo1 requested changes

2022-09-14 08:25 UTC, patrikk0123 commented on src/utils/patchHelper.tsx
> +export const createPatchData = (data: IFields): IFieldValues => {
I decided to use `transformFormToValues` since patch is in this terminology array of operations in JSON patch format rather than object of values.

2022-10-04 07:27 UTC, matedo1 requested changes
just minor change, thanks!

2022-10-04 07:27 UTC, matedo1 commented on src/components/ProjectCreateEditPage/ProjectCreateEditPage.tsx
> +              <ServiceContainerCreating {...dataContainerEditPatch} title="Edit Project">
let's rename this from `ServiceContainerCreating` to `ServiceContainerCreatingUpdating`

2022-10-04 07:27 UTC, matedo1 commented on src/services/projectService.ts
> +   * @param patchData - array of changes in JSON patch format
Maybe we could keep naming consistent with the official documentation https://www.npmjs.com/package/fast-json-patch , so:
`... in JSON-Patch format`

2022-10-04 15:14 UTC, matedo1 approved these changes

2022-10-04 16:51 UTC, merged